import type { Product as AdminProduct } from "./admin-api";
import localProducts from "@/data/products.json";

const rawProducts = [
  {
    id: "4a0b6f6a-e7c7-4764-9a7d-0e05052a2bde",
    name: "Casual Canvas Shoes",
    slug: "casual-canvas-shoes",
    description: "Casual Canvas Shoes — a premium footwear piece from Adidas, crafted for style and all-day comfort. Features a breathable dual-layer canvas upper, cushioned vulcanized rubber outsole, reinforced heel cup, and iconic low-profile silhouette suitable for daily street-ready wear.",
    shortDescription: "Breathable low-top canvas sneakers with vulcanized rubber sole and everyday cushioning.",
    status: "active",
    metaTitle: "Casual Canvas Shoes | Adidas Footwear",
    metaDescription: "Shop Adidas Casual Canvas Shoes at NovaMart. High quality canvas sneakers with cushioned soles and express delivery.",
    brandId: "6a89e34a-cc08-42d1-9bb4-8bf5f2e47856",
    categoryId: "a03a5df5-07df-4903-a084-58f77f9cba8e",
    unitId: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
    brand: {
      id: "6a89e34a-cc08-42d1-9bb4-8bf5f2e47856",
      name: "Adidas",
      slug: "adidas",
      logoUrl: null,
    },
    category: {
      id: "a03a5df5-07df-4903-a084-58f77f9cba8e",
      name: "Footwear",
      slug: "footwear",
    },
    unit: {
      id: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
      name: "Pair",
      abbreviation: "PR",
      factor: 1,
      isActive: true,
    },
    media: [
      {
        id: "m-ccs-1",
        isFeatured: true,
        sortOrder: 0,
        mediaId: "med-ccs-1",
        media: {
          id: "med-ccs-1",
          url: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
      {
        id: "m-ccs-2",
        isFeatured: false,
        sortOrder: 1,
        mediaId: "med-ccs-2",
        media: {
          id: "med-ccs-2",
          url: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
      {
        id: "m-ccs-3",
        isFeatured: false,
        sortOrder: 2,
        mediaId: "med-ccs-3",
        media: {
          id: "med-ccs-3",
          url: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
      {
        id: "m-ccs-4",
        isFeatured: false,
        sortOrder: 3,
        mediaId: "med-ccs-4",
        media: {
          id: "med-ccs-4",
          url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
    ],
    variants: [
      {
        id: "var-ccs-40-blk",
        sku: "ADI-CCS-BLK-40",
        price: "3200",
        cost: "4000",
        stockQuantity: 45,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Black" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 40 / US 7" } },
        ],
      },
      {
        id: "var-ccs-41-blk",
        sku: "ADI-CCS-BLK-41",
        price: "3200",
        cost: "4000",
        stockQuantity: 32,
        stockAlertThreshold: 5,
        isDefault: false,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Black" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 41 / US 8" } },
        ],
      },
      {
        id: "var-ccs-42-blk",
        sku: "ADI-CCS-BLK-42",
        price: "3200",
        cost: "4000",
        stockQuantity: 18,
        stockAlertThreshold: 5,
        isDefault: false,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Black" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 42 / US 8.5" } },
        ],
      },
      {
        id: "var-ccs-43-blk",
        sku: "ADI-CCS-BLK-43",
        price: "3200",
        cost: "4000",
        stockQuantity: 8,
        stockAlertThreshold: 5,
        isDefault: false,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Black" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 43 / US 9.5" } },
        ],
      },
      {
        id: "var-ccs-41-wht",
        sku: "ADI-CCS-WHT-41",
        price: "3200",
        cost: "4000",
        stockQuantity: 25,
        stockAlertThreshold: 5,
        isDefault: false,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "White" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 41 / US 8" } },
        ],
      },
      {
        id: "var-ccs-42-wht",
        sku: "ADI-CCS-WHT-42",
        price: "3200",
        cost: "4000",
        stockQuantity: 15,
        stockAlertThreshold: 5,
        isDefault: false,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "White" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 42 / US 8.5" } },
        ],
      },
    ],
  },
  {
    id: "439987bd-aaf4-4ffa-a1dc-c77b92806061",
    name: "Air Running Sneakers",
    slug: "air-running-sneakers",
    description: "Air Running Sneakers — engineered by Nike for high-performance athletes and urban runners alike. Features responsive Max-Air heel cushioning, dynamic engineered mesh upper for optimized air ventilation, and multi-directional flex grooves for exceptional road grip.",
    shortDescription: "High-performance road running sneakers with Max-Air cushioning and breathable mesh.",
    status: "active",
    metaTitle: "Nike Air Running Sneakers | NovaMart",
    metaDescription: "Shop authentic Nike Air Running Sneakers at NovaMart. Responsive cushioning and lightweight breathability.",
    brandId: "3c51db39-a8fc-4128-9728-f7cbbfcee421",
    categoryId: "a03a5df5-07df-4903-a084-58f77f9cba8e",
    unitId: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
    brand: {
      id: "3c51db39-a8fc-4128-9728-f7cbbfcee421",
      name: "Nike",
      slug: "nike",
      logoUrl: null,
    },
    category: {
      id: "a03a5df5-07df-4903-a084-58f77f9cba8e",
      name: "Footwear",
      slug: "footwear",
    },
    unit: {
      id: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
      name: "Pair",
      abbreviation: "PR",
      factor: 1,
      isActive: true,
    },
    media: [
      {
        id: "m-ars-1",
        isFeatured: true,
        sortOrder: 0,
        mediaId: "med-ars-1",
        media: {
          id: "med-ars-1",
          url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
      {
        id: "m-ars-2",
        isFeatured: false,
        sortOrder: 1,
        mediaId: "med-ars-2",
        media: {
          id: "med-ars-2",
          url: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
    ],
    variants: [
      {
        id: "var-ars-41-red",
        sku: "NIK-ARS-RED-41",
        price: "7500",
        cost: "9500",
        stockQuantity: 30,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Red" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 41 / US 8" } },
        ],
      },
      {
        id: "var-ars-42-red",
        sku: "NIK-ARS-RED-42",
        price: "7500",
        cost: "9500",
        stockQuantity: 20,
        stockAlertThreshold: 5,
        isDefault: false,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Red" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 42 / US 8.5" } },
        ],
      },
    ],
  },
  {
    id: "2ee19e0c-0673-4330-a0e5-5f320361f819",
    name: "Leather Chelsea Boots",
    slug: "leather-chelsea-boots",
    description: "Leather Chelsea Boots — crafted from full-grain bovine leather with elasticated side gussets and pull tabs for an effortless slip-on experience. A timeless Zara silhouette pairing sleek formal elegance with everyday durability.",
    shortDescription: "Premium full-grain leather boots with elasticated gusset and cushioned insole.",
    status: "active",
    metaTitle: "Leather Chelsea Boots | Zara Footwear",
    metaDescription: "Shop Zara Leather Chelsea Boots at NovaMart. Timeless leather design with express doorstep delivery.",
    brandId: "151ff728-9ca0-4058-82fd-2c716dc73298",
    categoryId: "a03a5df5-07df-4903-a084-58f77f9cba8e",
    unitId: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
    brand: {
      id: "151ff728-9ca0-4058-82fd-2c716dc73298",
      name: "Zara",
      slug: "zara",
      logoUrl: null,
    },
    category: {
      id: "a03a5df5-07df-4903-a084-58f77f9cba8e",
      name: "Footwear",
      slug: "footwear",
    },
    unit: {
      id: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
      name: "Pair",
      abbreviation: "PR",
      factor: 1,
      isActive: true,
    },
    media: [
      {
        id: "m-lcb-1",
        isFeatured: true,
        sortOrder: 0,
        mediaId: "med-lcb-1",
        media: {
          id: "med-lcb-1",
          url: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
    ],
    variants: [
      {
        id: "var-lcb-41",
        sku: "ZAR-LCB-041",
        price: "5200",
        cost: "6500",
        stockQuantity: 18,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Brown" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 41 / US 8" } },
        ],
      },
    ],
  },
  {
    id: "6f5c6765-53d0-4d68-a63d-390e6a5b980e",
    name: "Classic Stan Smith",
    slug: "classic-stan-smith",
    description: "Classic Stan Smith — iconic court sneaker redesigned by Adidas with sustainable vegan leather, subtle perforated 3-stripes, and a clean minimalist profile.",
    shortDescription: "Timeless court sneaker featuring perforated 3-stripes and clean white leather styling.",
    status: "active",
    metaTitle: "Adidas Classic Stan Smith | NovaMart",
    metaDescription: "Buy authentic Adidas Stan Smith sneakers with original packaging and verified guarantee.",
    brandId: "6a89e34a-cc08-42d1-9bb4-8bf5f2e47856",
    categoryId: "a03a5df5-07df-4903-a084-58f77f9cba8e",
    unitId: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
    brand: {
      id: "6a89e34a-cc08-42d1-9bb4-8bf5f2e47856",
      name: "Adidas",
      slug: "adidas",
      logoUrl: null,
    },
    category: {
      id: "a03a5df5-07df-4903-a084-58f77f9cba8e",
      name: "Footwear",
      slug: "footwear",
    },
    unit: {
      id: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
      name: "Pair",
      abbreviation: "PR",
      factor: 1,
      isActive: true,
    },
    media: [
      {
        id: "m-css-1",
        isFeatured: true,
        sortOrder: 0,
        mediaId: "med-css-1",
        media: {
          id: "med-css-1",
          url: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
    ],
    variants: [
      {
        id: "var-css-41",
        sku: "ADI-CSS-022",
        price: "6800",
        cost: "8000",
        stockQuantity: 28,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "White" } },
          { attributeValue: { attribute: { name: "Size" }, value: "EU 41 / US 8" } },
        ],
      },
    ],
  },
  {
    id: "ae205530-e02b-4fe1-8e3c-4779365644b8",
    name: "Slim Fit Jeans",
    slug: "slim-fit-jeans",
    description: "Slim Fit Jeans from Levi's — tailored from authentic stretch denim that moves with your body while retaining its clean shape. Classic 5-pocket styling with zip fly.",
    shortDescription: "Everyday stretch denim jeans with classic 5-pocket styling and tapered leg.",
    status: "active",
    metaTitle: "Levi's Slim Fit Jeans | NovaMart",
    metaDescription: "Authentic Levi's denim jeans with stretch comfort and tailored slim silhouette.",
    brandId: "lev-001",
    categoryId: "cat-men-01",
    unitId: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
    brand: {
      id: "lev-001",
      name: "Levi's",
      slug: "levis",
      logoUrl: null,
    },
    category: {
      id: "cat-men-01",
      name: "Men's Fashion",
      slug: "mens-fashion",
    },
    unit: {
      id: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
      name: "Piece",
      abbreviation: "PCS",
      factor: 1,
      isActive: true,
    },
    media: [
      {
        id: "m-sfj-1",
        isFeatured: true,
        sortOrder: 0,
        mediaId: "med-sfj-1",
        media: {
          id: "med-sfj-1",
          url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
    ],
    variants: [
      {
        id: "var-sfj-32",
        sku: "LEV-SFJ-032",
        price: "2200",
        cost: "2800",
        stockQuantity: 40,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Blue" } },
          { attributeValue: { attribute: { name: "Size" }, value: "32W x 32L" } },
        ],
      },
    ],
  },
  {
    id: "c1c5cc59-42fa-4ac7-942d-5dcf1e8e850d",
    name: "Oversized Blazer",
    slug: "oversized-blazer",
    description: "Oversized Blazer — a contemporary power-dressing piece from Mango, tailored from structured wool-blend suiting fabric with padded shoulders, notched lapels, and tortoiseshell button closure.",
    shortDescription: "Tailored wool-blend blazer with relaxed oversized fit and flap pockets.",
    status: "active",
    metaTitle: "Mango Oversized Blazer | NovaMart",
    metaDescription: "Shop Mango Oversized Blazer with structured fit and luxury tailoring at NovaMart.",
    brandId: "mng-001",
    categoryId: "cat-wom-01",
    unitId: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
    brand: {
      id: "mng-001",
      name: "Mango",
      slug: "mango",
      logoUrl: null,
    },
    category: {
      id: "cat-wom-01",
      name: "Women's Fashion",
      slug: "womens-fashion",
    },
    unit: {
      id: "c2ec2c89-05bc-4038-b0be-6aef04cbfa36",
      name: "Piece",
      abbreviation: "PCS",
      factor: 1,
      isActive: true,
    },
    media: [
      {
        id: "m-obz-1",
        isFeatured: true,
        sortOrder: 0,
        mediaId: "med-obz-1",
        media: {
          id: "med-obz-1",
          url: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=1000&auto=format&fit=crop&q=80",
          type: "image",
        },
      },
    ],
    variants: [
      {
        id: "var-obz-s",
        sku: "MNG-OBZ-S",
        price: "3800",
        cost: "4500",
        stockQuantity: 22,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Color" }, value: "Charcoal" } },
          { attributeValue: { attribute: { name: "Size" }, value: "S" } },
        ],
      },
    ],
  },
  // Also incorporate items from data/products.json
  ...(localProducts as any[]).map((lp) => ({
    id: lp.id,
    name: lp.name,
    slug: lp.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
    description: lp.description,
    shortDescription: lp.subtitle,
    status: "active",
    metaTitle: `${lp.name} | NovaMart`,
    metaDescription: lp.subtitle,
    brand: {
      id: `b-${lp.id}`,
      name: lp.collection || "Artisan Reserve",
      slug: (lp.collection || "artisan-reserve").toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      logoUrl: null,
    },
    category: {
      id: `c-${lp.id}`,
      name: lp.category || "Beverages",
      slug: (lp.category || "beverages").toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    },
    unit: {
      id: `u-${lp.id}`,
      name: "Box",
      abbreviation: "BOX",
      factor: 1,
      isActive: true,
    },
    media: (lp.galleryImages || [lp.image]).map((img: string, idx: number) => ({
      id: `med-${lp.id}-${idx}`,
      isFeatured: idx === 0,
      sortOrder: idx,
      mediaId: `med-id-${lp.id}-${idx}`,
      media: {
        id: `med-id-${lp.id}-${idx}`,
        url: img,
        type: "image",
      },
    })),
    variants: [
      {
        id: `var-${lp.id}-std`,
        sku: `ART-${lp.id}-001`,
        price: String(lp.priceNum || 2000),
        cost: String(lp.priceNum ? lp.priceNum + 500 : 2500),
        stockQuantity: 50,
        stockAlertThreshold: 5,
        isDefault: true,
        attributes: [
          { attributeValue: { attribute: { name: "Edition" }, value: "Collector's Pack" } },
        ],
      },
    ],
  })),
];

export const FALLBACK_MARKETPLACE_PRODUCTS: AdminProduct[] = rawProducts as unknown as AdminProduct[];
